import {BASE} from "@/lib/host-path";
"use client";
import {useEffect,useRef,useState} from "react";
import * as T from "three";
import {Decor,Look,Player,Furniture,furnitureNames} from "@/lib/world-types";
type Props={title:string;sign:string;light:number;scanlines:boolean;decor:Decor;players:Player[];selfId:string;look:Look;name:string;editing:boolean;selected:string;visit:string|null;video:HTMLVideoElement|null;onVisitDone:()=>void;onInteract:(kind:string)=>void;onSelect:(id:string)=>void;onMotion:(p:{x:number;z:number;r:number;seat:string})=>void;onNeedName:()=>void};
const sizes:Record<string,[number,number]>={tv:[2.5,1],console:[1.5,.9],arcade:[1.1,1.2],books:[1.5,.65],sofa:[3,1.15],table:[1.8,1],plant:[.7,.7],lamp:[.6,.6],speakers:[1,.75]};
function labelTexture(text:string,bg="#282438",fg="#ece5c9",w=512,h=128){const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d")!;x.fillStyle=bg;x.fillRect(0,0,w,h);x.fillStyle=fg;x.font=`bold ${Math.min(64,w/(Math.max(text.length,1)*.64))}px monospace`;x.textAlign="center";x.textBaseline="middle";x.fillText(text,w/2,h/2,w-20);const t=new T.CanvasTexture(c);t.magFilter=T.NearestFilter;t.colorSpace=T.SRGBColorSpace;return t;}
function box(parent:T.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,color:string){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.86,flatShading:true}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function textPlane(g:T.Object3D,text:string,w:number,h:number,x:number,y:number,z:number,bg?:string,fg?:string){const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:labelTexture(text,bg,fg)}));m.position.set(x,y,z);g.add(m);return m;}
function cylinder(g:T.Object3D,rad:number,h:number,x:number,y:number,z:number,color:string,segments=8){const m=new T.Mesh(new T.CylinderGeometry(rad,rad,h,segments),new T.MeshStandardMaterial({color,flatShading:true}));m.position.set(x,y,z);m.castShadow=true;g.add(m);return m;}
function avatar(look:Look,name:string){const g=new T.Group();const root=new T.Group();g.add(root);box(root,.37,.46,.23,0,.86,0,look.top);box(root,.35,.32,.3,0,1.26,0,look.skin);box(root,.37,.11,.32,0,1.45,0,look.hair);if(look.style===1){box(root,.1,.32,.3,-.16,1.27,0,look.hair);box(root,.1,.32,.3,.16,1.27,0,look.hair);}if(look.style===2){box(root,.47,.12,.4,0,1.49,0,look.top);box(root,.42,.04,.25,0,1.43,.23,look.top);}box(root,.045,.045,.01,-.075,1.29,.158,"#302c3b");box(root,.045,.045,.01,.075,1.29,.158,"#302c3b");const limbs:T.Group[]=[];for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.255,1,0);box(arm,.12,.34,.14,0,-.12,0,look.top);box(arm,.13,.12,.14,0,-.33,0,look.skin);root.add(arm);limbs.push(arm);}for(const side of [-1,1]){const leg=new T.Group();leg.position.set(side*.1,.67,0);box(leg,.145,.39,.17,0,-.18,0,look.bottom);box(leg,.17,.12,.26,0,-.4,.04,"#e7dac4");root.add(leg);limbs.push(leg);}const sprite=new T.Sprite(new T.SpriteMaterial({map:labelTexture(name||"YOU","#292331","#f3efd9"),depthTest:false}));sprite.scale.set(Math.max(1.8,Math.min(3.6,name.length*.15)),.4,1);sprite.position.y=1.92;g.add(sprite);g.userData={limbs,root,sprite};return g;}
function furniture(o:Furniture){const g=new T.Group();g.position.set(o.x,0,o.z);g.rotation.y=o.r*Math.PI/180;g.userData={id:o.id,kind:o.kind};const dark="#2e2c3e",wood="#845a49";
if(o.kind==="tv"){box(g,2.55,.6,.85,0,.33,0,wood);box(g,2.25,1.45,.68,0,1.37,0,"#4c4552");box(g,1.85,1.11,.1,-.12,1.39,.39,dark);const screen=textPlane(g,"SELECT A TAPE",1.74,.99,-.12,1.39,.449,"#1c3341","#82cfb3");screen.userData.tv=true;box(g,.2,.12,.06,1,1.7,.38,"#cebe9c");box(g,.2,.12,.06,1,1.4,.38,"#cebe9c");for(let i=0;i<5;i++)box(g,.22,.035,.025,1,1.05+i*.055,.385,"#222330");for(let i=0;i<5;i++)box(g,.18,.18,.4,-.85+i*.32,.22,.3,["#9d7969","#767fa5","#749587"][i%3]);}
if(o.kind==="console"){box(g,1.5,.6,.85,0,.3,0,wood);box(g,.94,.2,.57,0,.72,0,"#aaa5b6");cylinder(g,.21,.015,0,.83,0,"#737384",20);box(g,.12,.04,.1,-.32,.85,.1,"#92b998");textPlane(g,"CONSOLE",1.15,.2,0,.4,.436,"#503b3c","#e2d4c2");box(g,.34,.1,.17,.47,.72,.5,"#595167");box(g,.34,.1,.17,-.47,.72,.5,"#595167");}
if(o.kind==="arcade"){box(g,1.05,1.9,1,0,1,0,"#584176");box(g,.93,.23,1.14,0,1.08,.14,"#d89372");box(g,.83,.77,.1,0,1.6,.55,dark);textPlane(g,"PRESS START",.77,.66,0,1.63,.61,"#172c3a","#aaebc2");box(g,1.12,.35,1.08,0,2.2,0,"#bd7894");textPlane(g,"ARCADE",.93,.24,0,2.2,.55,"#382740","#f3c28a");cylinder(g,.04,.16,-.2,1.29,.48,"#171c2b");cylinder(g,.08,.07,-.2,1.38,.48,"#a9b3d0");for(let i=0;i<3;i++)cylinder(g,.045,.025,.09+i*.12,1.21,.52,["#ee9d87","#a2dabb","#b7acf0"][i]);}
if(o.kind==="books"){box(g,1.55,2.3,.55,0,1.2,0,"#4c3740");for(let k=0;k<4;k++){box(g,1.65,.085,.67,0,.17+k*.58,0,"#a8775b");for(let i=0;i<8;i++){box(g,.115,.29+(i%3)*.045,.35,-.65+i*.18,.39+k*.58,.19,["#a885af","#ae735d","#678c91","#cfb176","#9caa84"][i%5]);}}textPlane(g,"BOOKS",1.3,.18,0,2.3,.3,"#473038","#d5c6a5");}
if(o.kind==="sofa"){box(g,3,.42,1.1,0,.4,0,"#78667d");box(g,3,.82,.28,0,.84,-.43,"#81708f");for(const x of [-1.36,1.36])box(g,.29,.72,1.15,x,.64,0,"#92839d");for(const x of [-.87,0,.87])box(g,.83,.21,.79,x,.71,.1,"#a497b0");box(g,.47,.42,.16,-.84,1,-.22,"#c68e77");box(g,.47,.42,.16,.84,1,-.22,"#90ab98");for(const x of [-1.1,1.1])for(const z of [-.35,.35])box(g,.13,.23,.13,x,.15,z,"#332e3c");}
if(o.kind==="table"){box(g,1.8,.12,1,0,.49,0,"#b58766");for(const x of [-.7,.7])for(const z of [-.35,.35])box(g,.1,.47,.1,x,.235,z,"#4b3740");box(g,.5,.05,.35,-.35,.58,0,"#a99ac0");cylinder(g,.09,.2,.4,.66,.1,"#bcd6bc");}
if(o.kind==="lamp"){cylinder(g,.35,.1,0,.1,0,"#4b4052");cylinder(g,.035,1.6,0,.9,0,"#b79c77");const shade=new T.Mesh(new T.CylinderGeometry(.28,.47,.49,8),new T.MeshStandardMaterial({color:"#e6c598",emissive:"#c99860",emissiveIntensity:.35,flatShading:true}));shade.position.y=1.77;g.add(shade);const light=new T.PointLight("#ffce91",8,5,2);light.position.set(0,1.5,0);g.add(light);}
if(o.kind==="plant"){cylinder(g,.26,.49,0,.28,0,"#b18470");for(let i=0;i<7;i++){const leaf=new T.Mesh(new T.ConeGeometry(.18,.95,4),new T.MeshStandardMaterial({color:i%2?"#7f9d84":"#9bb197",flatShading:true}));leaf.position.set(Math.sin(i)*.25,.9+(i%2)*.25,Math.cos(i)*.25);leaf.rotation.z=Math.sin(i)*.4;g.add(leaf);}}
if(o.kind==="speakers"){for(const x of [-.28,.28]){box(g,.45,1.05,.6,x,.58,0,"#4b4047");for(const y of [.35,.8]){const disc=new T.Mesh(new T.CylinderGeometry(.16,.16,.025,12),new T.MeshStandardMaterial({color:"#212633"}));disc.rotation.x=Math.PI/2;disc.position.set(x,y,.32);g.add(disc);}}}
return g;}
function dispose(obj:T.Object3D){obj.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Sprite){if(o instanceof T.Mesh)o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if("map" in m&&(m as T.MeshBasicMaterial).map)(m as T.MeshBasicMaterial).map?.dispose();m.dispose();});}});}
export default function BasementWorld(props:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(props),engine=useRef<{rebuild:()=>void;visit:(id:string)=>void;reset:()=>void}|null>(null);latest.current=props;const [hint,setHint]=useState("Click a floor tile to walk"),[failed,setFailed]=useState(false);
useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:false,alpha:true,powerPreference:"high-performance"});}catch{setFailed(true);return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor("#201e2c",0);el.appendChild(renderer.domElement);const scene=new T.Scene();const camera=new T.OrthographicCamera(-9,9,7,-7,.1,100);camera.position.set(12,12,15);camera.lookAt(0,.2,0);let zoom=1;const hemi=new T.HemisphereLight("#e5defc","#74606b",2.4);scene.add(hemi);const sun=new T.DirectionalLight("#fff0d7",3);sun.position.set(4,10,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.bias=-.001;scene.add(sun);const rim=new T.DirectionalLight("#b9afff",2);rim.position.set(-5,4,-5);scene.add(rim);
let architecture=new T.Group(),items=new T.Group();scene.add(architecture,items);const avatars=new Map<string,T.Group>();let me=new T.Vector3(0,0,3.6),angle=Math.PI,seat="",path:T.Vector3[]=[],pending:(()=>void)|null=null;const ray=new T.Raycaster(),mouse=new T.Vector2(),targetMarker=new T.Mesh(new T.RingGeometry(.13,.21,24),new T.MeshBasicMaterial({color:"#f2cfa0",side:T.DoubleSide,transparent:true,opacity:.8}));targetMarker.rotation.x=-Math.PI/2;targetMarker.visible=false;scene.add(targetMarker);let videoTexture:T.VideoTexture|null=null,lastVideo:HTMLVideoElement|null=null;
function rebuild(){scene.remove(architecture,items);dispose(architecture);dispose(items);architecture=new T.Group();items=new T.Group();scene.add(architecture,items);const d=latest.current.decor;box(architecture,12.2,.3,10.2,0,-.18,0,"#373042");const floor=box(architecture,12,.08,10,0,-.005,0,d.floor);floor.userData.floor=true;for(let x=-6;x<=6;x+=.6){box(architecture,.017,.015,10,x,.044,0,"#4c3d40");for(let z=-5;z<5;z+=2){box(architecture,.58,.015,.018,x+.3,.045,z+(Math.round(x*10)%2?.65:0),"#4c3d40");}}
box(architecture,12,.16,.16,0,.12,5,"#be9678");box(architecture,.18,3.35,10,-6,1.61,0,d.wall);box(architecture,12,3.35,.18,0,1.61,-5,d.wall);for(let y=.45;y<3.3;y+=.55){box(architecture,11.9,.025,.025,0,y,-4.89,"#3c374e");box(architecture,.025,.025,9.9,-5.89,y,0,"#3c374e");}box(architecture,12,.12,.13,0,3.3,-4.95,"#887897");box(architecture,.13,.12,10,-5.95,3.3,0,"#887897");const neon=box(architecture,3.7,.045,.06,-1.5,2.85,-4.84,d.neon);(neon.material as T.MeshStandardMaterial).emissive.set(d.neon);(neon.material as T.MeshStandardMaterial).emissiveIntensity=2;textPlane(architecture,latest.current.title.toUpperCase(),3.3,.42,-1.5,2.47,-4.84,"#393247","#d5c5f0");
box(architecture,4.2,.015,3.4,-2.4,.052,1.1,"#66596f");for(let i=0;i<4;i++){box(architecture,3.95-i*.18,.015,.06,-2.4,.066,-.48+i*.12,"#b599a9");box(architecture,3.95-i*.18,.015,.06,-2.4,.066,2.68-i*.12,"#b599a9");}
textPlane(architecture,latest.current.sign,3.8,.24,2.6,2.9,-4.84,"#393247","#ccb9d5");for(let i=0;i<3;i++){const frame=new T.Group();frame.userData={id:"art-"+i,kind:"art"};frame.position.set(-5.84,1.9,-3.1+i*2.8);frame.rotation.y=Math.PI/2;box(frame,1.45,1.5,.1,0,0,0,"#c3a082");const plane=textPlane(frame,["YOUR ART","MAKE SPACE","STAY AWHILE"][i],1.28,1.33,0,0,.06,["#6a617d","#617983","#927764"][i],"#eddec4");const asset=d.art[i];if(asset)new T.TextureLoader().load(BASE+"/api/files/"+asset,t=>{t.colorSpace=T.SRGBColorSpace;t.magFilter=T.NearestFilter;const aspect=t.image.width/t.image.height;plane.scale.set(aspect>1?1:aspect,aspect>1?1/aspect:1,1);(plane.material as T.MeshBasicMaterial).map?.dispose();(plane.material as T.MeshBasicMaterial).map=t;(plane.material as T.MeshBasicMaterial).needsUpdate=true;},undefined,()=>{});items.add(frame);}
for(const o of d.objects){const g=furniture(o);if(latest.current.editing&&latest.current.selected===o.id){const outline=new T.BoxHelper(g,0xf4cea1);g.add(outline);}items.add(g);}lastVideo=null;}
function blocked(x:number,z:number){return latest.current.decor.objects.some(o=>{const [w,d]=sizes[o.kind]||[1,1],a=-o.r*Math.PI/180,dx=x-o.x,dz=z-o.z,rx=dx*Math.cos(a)+dz*Math.sin(a),rz=-dx*Math.sin(a)+dz*Math.cos(a);return Math.abs(rx)<w/2+.18&&Math.abs(rz)<d/2+.18;});}
function route(goal:T.Vector3){if(seat){const id=seat.slice(0,seat.lastIndexOf(":")),o=latest.current.decor.objects.find(o=>o.id===id);if(o){const a=o.r*Math.PI/180;me.set(o.x+Math.sin(a)*((sizes[o.kind]?.[1]||1)/2+.4),0,o.z+Math.cos(a)*((sizes[o.kind]?.[1]||1)/2+.4));}seat="";}if(blocked(me.x,me.z)){let free:T.Vector3|null=null,best=Infinity;for(let x=-5.6;x<5.7;x+=.4)for(let z=-4.6;z<4.7;z+=.4){const d=Math.hypot(x-me.x,z-me.z);if(d<best&&!blocked(x,z)){best=d;free=new T.Vector3(x,0,z);}}if(free)me.copy(free);}const step=.25,nx=45,nz=37;const snap=(v:T.Vector3)=>[Math.max(0,Math.min(nx-1,Math.round((v.x+5.5)/step))),Math.max(0,Math.min(nz-1,Math.round((v.z+4.5)/step)))];const [sx,sz]=snap(me),[gx,gz]=snap(goal),start=sx+sz*nx,goalId=gx+gz*nx,queue=[start],prev=new Map<number,number>([[start,-1]]);let end=-1;for(let k=0;k<queue.length;k++){const v=queue[k],x=v%nx,z=Math.floor(v/nx);if(v===goalId){end=v;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz,id=xx+zz*nx;if(xx<0||zz<0||xx>=nx||zz>=nz||prev.has(id)||blocked(xx*step-5.5,zz*step-4.5))continue;prev.set(id,v);queue.push(id);}}if(end<0){setHint("That spot is blocked. Try a nearby floor tile.");return false;}const points:T.Vector3[]=[];while(end!==start){points.unshift(new T.Vector3((end%nx)*step-5.5,0,Math.floor(end/nx)*step-4.5));end=prev.get(end)!;}path=points;seat="";targetMarker.position.copy(goal);targetMarker.position.y=.095;targetMarker.visible=true;return true;}
function visit(id:string){if(id==="__stand"){pending=null;route(new T.Vector3(0,0,3.6));return;}if(!latest.current.name){latest.current.onNeedName();return;}if(id.startsWith("art-")){const i=Number(id.slice(4));if(route(new T.Vector3(-4.5,0,-3.1+i*2.8)))pending=()=>latest.current.onInteract("art");return;}const o=latest.current.decor.objects.find(o=>o.id===id);if(!o)return;if(latest.current.editing){latest.current.onSelect(id);return;}const a=o.r*Math.PI/180,front=(sizes[o.kind]?.[1]||1)/2+.4,goal=new T.Vector3(o.x+Math.sin(a)*front,0,o.z+Math.cos(a)*front);const sides=[goal,...[-1,1].map(side=>new T.Vector3(o.x+Math.cos(a)*((sizes[o.kind]?.[0]||1)/2+.4)*side,0,o.z-Math.sin(a)*((sizes[o.kind]?.[0]||1)/2+.4)*side))];if(sides.some(g=>route(g))){pending=()=>{angle=a+Math.PI;if(o.kind==="sofa"){const n=[0,1,2].find(n=>!latest.current.players.some(p=>p.id!==latest.current.selfId&&p.seat===o.id+":"+n));if(n===undefined){setHint("The sofa is full. Pick another spot.");return;}seat=o.id+":"+n;const xx=(n-1)*.82;me.set(o.x+xx*Math.cos(a)+.15*Math.sin(a),0,o.z-xx*Math.sin(a)+.15*Math.cos(a));angle=a;setHint("Sitting on the sofa · click the floor to stand");}else if(["tv","console","arcade","books","speakers"].includes(o.kind))latest.current.onInteract(o.kind);else setHint("Use Decorate to move or recolour the room.");};setHint("Walking to "+furnitureNames[o.kind]);}}
function hit(e:PointerEvent){const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);return ray.intersectObjects([items,architecture],true).find(h=>{let o:T.Object3D|null=h.object;while(o){if(o.userData.id||o.userData.floor)return true;o=o.parent;}return false;});}
function clicked(e:PointerEvent){const h=hit(e);if(!h)return;let o:T.Object3D|null=h.object;while(o&&!o.userData.id&&!o.userData.floor)o=o.parent;if(o?.userData.id)visit(o.userData.id);else if(!latest.current.editing){if(!latest.current.name){latest.current.onNeedName();return;}pending=null;if(route(h.point))setHint("Walking…");}}
function wheel(e:WheelEvent){e.preventDefault();zoom=Math.max(.65,Math.min(1.6,zoom-e.deltaY*.0006));resize();}
function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);const aspect=w/Math.max(h,1),vertical=Math.max(7.5,9/aspect)/zoom;camera.left=-vertical*aspect;camera.right=vertical*aspect;camera.top=vertical;camera.bottom=-vertical;camera.updateProjectionMatrix();}
const observer=new ResizeObserver(resize);observer.observe(el);renderer.domElement.addEventListener("pointerup",clicked);renderer.domElement.addEventListener("wheel",wheel,{passive:false});engine.current={rebuild,visit,reset:()=>{zoom=1;resize();}};rebuild();resize();let last=performance.now(),frame=0,emit=0;
function animate(now:number){frame=requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;const p=latest.current;hemi.intensity=2.4*p.light/85;sun.intensity=3*p.light/85;if(path.length){const next=path[0],dir=next.clone().sub(me),dist=dir.length();angle=Math.atan2(dir.x,dir.z);if(dist<dt*2.4){me.copy(next);path.shift();}else me.addScaledVector(dir.normalize(),dt*2.4);if(!path.length){targetMarker.visible=false;const action=pending;pending=null;action?.();}}
const seen=new Set<string>();const all=[...p.players.filter(x=>x.id!==p.selfId),{id:"self",name:p.name||"You",x:me.x,z:me.z,r:angle,seat,look:p.look,at:now}];for(const person of all){seen.add(person.id);let g=avatars.get(person.id);const signature=JSON.stringify(person.look)+person.name;if(!g||g.userData.signature!==signature){if(g){scene.remove(g);dispose(g);}g=avatar(person.look,person.name);g.userData.signature=signature;g.position.set(person.x,0,person.z);avatars.set(person.id,g);scene.add(g);}const dist=Math.hypot(person.x-g.position.x,person.z-g.position.z);g.position.x=T.MathUtils.lerp(g.position.x,person.x,person.id==="self"?1:Math.min(1,dt*5));g.position.z=T.MathUtils.lerp(g.position.z,person.z,person.id==="self"?1:Math.min(1,dt*5));g.rotation.y=person.r;const walking=person.id==="self"?path.length>0:dist>.05;const limbs=g.userData.limbs as T.Group[];limbs.forEach((l,i)=>l.rotation.x=person.seat?(i>1?-Math.PI/2:0):walking?Math.sin(now*.012+(i%2)*Math.PI)*.55:0);g.userData.root.position.y=person.seat?.06:walking?Math.abs(Math.sin(now*.012))*.035:0;g.userData.sprite.position.y=person.seat?1.95:1.92;}
for(const [id,g] of avatars)if(!seen.has(id)){scene.remove(g);dispose(g);avatars.delete(id);}if(p.video!==lastVideo){videoTexture?.dispose();videoTexture=p.video?new T.VideoTexture(p.video):null;if(videoTexture)videoTexture.colorSpace=T.SRGBColorSpace;items.traverse(o=>{if(o.userData.tv&&o instanceof T.Mesh){const m=o.material as T.MeshBasicMaterial;m.map=videoTexture||labelTexture("SELECT A TAPE","#1c3341","#82cfb3");m.needsUpdate=true;}});lastVideo=p.video;}if(now-emit>150){p.onMotion({x:me.x,z:me.z,r:angle,seat});emit=now;}renderer.render(scene,camera);}
frame=requestAnimationFrame(animate);return()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener("pointerup",clicked);renderer.domElement.removeEventListener("wheel",wheel);dispose(scene);videoTexture?.dispose();renderer.dispose();renderer.domElement.remove();engine.current=null;};},[]);
useEffect(()=>{engine.current?.rebuild();},[JSON.stringify(props.decor),props.editing,props.selected,props.title,props.sign]);useEffect(()=>{if(props.visit){engine.current?.visit(props.visit);props.onVisitDone();}},[props.visit]);return <div className={"iso-stage "+(props.scanlines?"pixel-scanlines":"")}><div ref={host} className="three-host" aria-label="Isometric basement. Click floor tiles to walk; click furniture to use it."/>{failed&&<div className="webgl-error">Your browser could not start the 3D room. Enable hardware acceleration and reload. Your chat and saved collections are still available.</div>}<div className="room-hint"><span className="keycap">CLICK</span>{props.editing?"Select furniture to move or rotate it":hint}</div><button className="reset-camera" onClick={()=>engine.current?.reset()}>Reset view</button></div>;
}
