import {BASE} from "@/lib/host-path";
"use client";
import {useRef,useState} from "react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Progress} from "@/components/ui/progress";
import {Upload,Play,BookOpen,Trash2,Image as ImageIcon,Gamepad2,File,ArrowLeft} from "lucide-react";
import {toast} from "sonner";
import {Asset,Decor} from "@/lib/world-types";
import {uploadLimit,UPLOAD_CHUNK_BYTES} from "@/lib/upload-limits";
export const coreNames:Record<string,string>={nes:"NES",snes:"Super Nintendo",gb:"Game Boy / Color",gba:"Game Boy Advance",segaMD:"Mega Drive",n64:"Nintendo 64",psx:"PlayStation",arcade:"Arcade (MAME)"};
type Props={kind:string|null;setKind:(k:string|null)=>void;files:Asset[];roomKey:string;ensureJoined:()=>Promise<boolean>;refresh:()=>Promise<void>;decor:Decor;saveDecor:(d:Decor)=>Promise<void>;onPlay:(a:Asset)=>void;playing:Asset|null;video:HTMLVideoElement|null};
export default function RoomCollection(p:Props){const [progress,setProgress]=useState(-1),[core,setCore]=useState("nes"),[bios,setBios]=useState("none"),[game,setGame]=useState<Asset|null>(null),[reading,setReading]=useState<Asset|null>(null),[remove,setRemove]=useState<Asset|null>(null),[busy,setBusy]=useState(false),[tab,setTab]=useState("rom");const input=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null);const kind=p.kind==="console"||p.kind==="arcade"?tab:p.kind==="books"?"book":p.kind==="tv"||p.kind==="speakers"?"media":p.kind==="art"?"art":"media";const files=p.files.filter(a=>a.kind===kind);const titles:Record<string,string>={tv:"THE TELEVISION",speakers:"THE STEREO",console:"CONSOLE STATION",arcade:"ARCADE CABINET",books:"THE BOOKSHELF",art:"ON THE WALL"};
async function request(body:unknown){const r=await fetch(BASE+"/api/library",{method:"POST",headers:{"x-room-key":p.roomKey,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as {error?:string;id?:string};if(!r.ok)throw new Error(d.error||"Something went wrong");return d;}
async function upload(f:File){if(progress>=0)return;if(!await p.ensureJoined())return;const limit=uploadLimit(kind);if(f.size>limit.bytes){toast.error(`The file limit is ${limit.label}.`);return;}setProgress(0);controller.current=new AbortController();let id:string|undefined;try{const start=await request({action:"start",filename:f.name,kind,core:p.kind==="arcade"?"arcade":core,size:f.size});id=start.id;const chunk=UPLOAD_CHUNK_BYTES;for(let offset=0,part=1;offset<f.size;offset+=chunk,part++){const r=await fetch(`${BASE}/api/library?id=${id}&part=${part}`,{method:"PUT",headers:{"x-room-key":p.roomKey},body:f.slice(offset,offset+chunk),signal:controller.current.signal});if(!r.ok){const d=await r.json() as {error?:string};throw new Error(d.error||"Upload failed");}setProgress(Math.round(Math.min(f.size,offset+chunk)/f.size*100));}await request({action:"finish",id});await p.refresh();toast.success("Added to your collection");}catch(e){if(id)await request({action:"cancel",id}).catch(()=>{});toast.error(e instanceof DOMException&&e.name==="AbortError"?"Upload cancelled":(e as Error).message);}finally{setProgress(-1);controller.current=null;if(input.current)input.current.value="";}}
async function activate(a:Asset){if(!await p.ensureJoined())return;if(a.kind==="media"){p.onPlay(a);p.setKind(null);}else if(a.kind==="rom"){setGame(a);}else if(a.kind==="book")setReading(a);}
function close(open:boolean){if(!open){if(progress>=0){toast("Finish or cancel the upload first.");return;}p.setKind(null);setGame(null);setReading(null);}}
const accept:Record<string,string>={media:".mp4,.webm,.mp3,.ogg,.wav,.m4a",book:".pdf,.txt",art:".jpg,.jpeg,.png,.webp,.gif",rom:".nes,.sfc,.smc,.gb,.gbc,.gba,.md,.gen,.bin,.zip,.7z,.n64,.z64,.v64,.iso,.chd,.pbp",bios:".bin,.rom,.zip"};
return <><Dialog open={!!p.kind} onOpenChange={close}><DialogContent className="collection-window"><DialogTitle>{titles[p.kind||""]||"COLLECTION"}</DialogTitle><DialogDescription>{kind==="media"?"Your saved tapes and records. Choose one to play in the room.":kind==="book"?"Add PDFs and text files to your bookshelf.":kind==="art"?"Upload a picture and choose a wall frame.":"Add your own ROM files and match them to the right system."}</DialogDescription>{game?<><button className="retro-button" onClick={()=>setGame(null)}><ArrowLeft size={16}/>Back to games</button><iframe className="emulator-frame" title={game.filename} src={`${BASE}/emulator.html#${new URLSearchParams({rom:game.id,core:game.core,name:game.filename,...(bios!=="none"?{bios,biosName:p.files.find(a=>a.id===bios)?.filename||"bios.bin"}:{})}).toString()}`} allow="autoplay; fullscreen; gamepad" allowFullScreen/><p className="collection-note">Game controls, controller mapping and save states are in the emulator menu. Game saves stay in this browser; export them there for backup.</p></>:reading?<><button className="retro-button" onClick={()=>setReading(null)}><ArrowLeft size={16}/>Back to books</button><iframe className="book-frame" title={reading.filename} src={BASE+"/api/files/"+reading.id}/><a className="file-open" href={BASE+"/api/files/"+reading.id} target="_blank" rel="noreferrer">Open {reading.filename} in a new tab</a></>:<>
{["console","arcade"].includes(p.kind||"")&&<div className="console-options"><div className="segmented"><button className={tab==="rom"?"active":""} onClick={()=>setTab("rom")}>Games</button><button className={tab==="bios"?"active":""} onClick={()=>setTab("bios")}>BIOS files</button></div>{p.kind!=="arcade"&&<label>Upload system<Select value={core} onValueChange={setCore}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(coreNames).map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select></label>}<label>BIOS for next launch<Select value={bios} onValueChange={setBios}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">None / core default</SelectItem>{p.files.filter(a=>a.kind==="bios").map(a=><SelectItem key={a.id} value={a.id}>{a.filename}</SelectItem>)}</SelectContent></Select></label></div>}
<div className="upload-row"><input ref={input} type="file" hidden accept={accept[kind]} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);}}/><button className="retro-button bright" disabled={progress>=0} onClick={()=>input.current?.click()}><Upload size={17}/>Add {kind==="rom"?"ROM":kind==="bios"?"BIOS":kind==="art"?"artwork":kind==="book"?"book":"media"}</button><span>{uploadLimit(kind).label} per file · saved with this room</span></div>{progress>=0&&<div className="upload-progress"><Progress value={progress}/><span>Uploading {progress}%</span><button onClick={()=>controller.current?.abort()}>Cancel</button></div>}
{files.length===0?<div className="collection-empty"><File size={36}/><h3>{kind==="rom"?"Your next game goes here.":kind==="art"?"Bare walls, endless possibilities.":"There’s room on the shelf."}</h3><p>Use the add button to start your collection.</p></div>:<div className={"file-grid "+(kind==="art"?"art-grid":"")}>{files.map(a=><article className="file-card" key={a.id}>{a.kind==="art"?<img src={BASE+"/api/files/"+a.id} alt={a.filename}/>:<span className="file-icon">{a.kind==="rom"?<Gamepad2/>:a.kind==="book"?<BookOpen/>:a.kind==="bios"?<File/>:<Play/>}</span>}<div className="file-info"><strong>{a.filename}</strong><small>{a.kind==="rom"?coreNames[a.core]+" · ":""}{(a.size/1024/1024).toFixed(1)} MB</small></div>{a.kind==="art"?<div className="hang-actions">{[0,1,2].map(i=><button key={i} onClick={()=>{const art=[...p.decor.art];art[i]=a.id;p.saveDecor({...p.decor,art}).then(()=>toast.success("Hung in frame "+(i+1))).catch(()=>toast.error("Could not hang artwork"));}}>{p.decor.art[i]===a.id?"✓ ":""}Frame {i+1}</button>)}</div>:a.kind!=="bios"&&<button className="retro-button" onClick={()=>activate(a)}>{a.kind==="book"?"Read":a.kind==="rom"?"Play game":"Play"}</button>}<button className="delete-file" aria-label={"Delete "+a.filename} onClick={()=>setRemove(a)}><Trash2 size={15}/></button></article>)}</div>}
{["console","arcade"].includes(p.kind||"")&&<p className="collection-note">Powered by <a href="https://emulatorjs.org/docs/" target="_blank" rel="noreferrer">EmulatorJS</a>. Choose a matching BIOS if your system needs one. ZIP multi-file disc games together. PS2 is not supported. Emulator loading needs an internet connection; game compatibility varies.</p>}{kind==="media"&&<p className="collection-note">MP4 / WebM video and MP3 / OGG / WAV / M4A audio. Playback depends on the file’s codec. Playback is personal for now; watch-together synchronisation is not yet included.</p>}</>}
</DialogContent></Dialog><AlertDialog open={!!remove} onOpenChange={o=>{if(!o&&!busy)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this file?</AlertDialogTitle><AlertDialogDescription>{remove?.filename} will be deleted from this room’s collection for everyone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep file</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(!remove)return;setBusy(true);try{await request({action:"delete",id:remove.id});await p.refresh();setRemove(null);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>{busy?"Removing…":"Remove file"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
