import {BASE} from "@/lib/host-path";
"use client";
import BasementWorld from "@/components/basement-world";
import RoomCollection from "@/components/room-collection";
import {defaultDecor,defaultLook,furnitureNames,type Decor,type Look,type Player,type Asset} from "@/lib/world-types";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Tv,BookOpen,Image as ImageIcon,Shirt,MessageCircle,Settings,Plus,RotateCw,Move,Save,X,Maximize2} from "lucide-react";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {Headphones,Hash,Mic,MicOff,Volume2,VolumeX,PhoneOff,Gamepad2,SlidersHorizontal,Send,Link as LinkIcon,Sofa,ArrowUpRight,Users,Radio,Check,Palette} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {SidebarProvider,Sidebar,SidebarContent,SidebarFooter,SidebarTrigger} from "@/components/ui/sidebar";
import {Switch} from "@/components/ui/switch";
import {Slider} from "@/components/ui/slider";
import {Toaster,toast} from "sonner";
type Settings={title:string;topic:string;accent:string;labels:string[];light:number;poster:string;scanlines:boolean};
type Peer={id:string;name:string;voice:string};
type Message={id:number;name:string;body:string;at:number;sender:string};
type RoomState={me:string;messages:Message[];peers:Peer[];signals:{id:number;sender:string;body:string}[];settings:Settings|null};
const defaults:Settings={title:"The Basement",topic:"No quests. No deadlines. Just good company.",accent:"#b8e883",labels:["the-couch","game-night","random-stuff"],light:85,poster:"STAY A LITTLE LONGER",scanlines:true};
const channels=["general","game-night","off-topic"],voiceIds=["couch","arcade","quiet"],voiceNames=["The couch","Arcade corner","Quiet corner"];
export default function Home(){
const [settings,setSettings]=useState<Settings>(defaults),[draft,setDraft]=useState<Settings>(defaults),[custom,setCustom]=useState(false),[profile,setProfile]=useState(false),[name,setName]=useState(""),[nameDraft,setNameDraft]=useState(""),[room,setRoom]=useState("general"),[messages,setMessages]=useState<Message[]>([]),[peers,setPeers]=useState<Peer[]>([]),[text,setText]=useState(""),[ready,setReady]=useState(false),[online,setOnline]=useState(false),[sending,setSending]=useState(false),[saving,setSaving]=useState(false),[voice,setVoice]=useState(""),[muted,setMuted]=useState(false),[deaf,setDeaf]=useState(false),[joining,setJoining]=useState(false),[connections,setConnections]=useState(0),[invite,setInvite]=useState(false),[inviteUrl,setInviteUrl]=useState("");
const key=useRef(""),me=useRef(""),nameRef=useRef(""),roomRef=useRef(room),voiceRef=useRef(""),stream=useRef<MediaStream|null>(null),since=useRef(0),pcs=useRef(new Map<string,RTCPeerConnection>()),audios=useRef(new Map<string,HTMLAudioElement>()),ice=useRef(new Map<string,RTCIceCandidateInit[]>()),deafRef=useRef(false),pollBusy=useRef(false),scroll=useRef<HTMLDivElement>(null),bottom=useRef(true),lastBeat=useRef(0);
async function api<T=RoomState>(body?:unknown,query=""):Promise<T>{const r=await fetch(BASE+"/api/lounge"+query,{method:body?"POST":"GET",headers:{"x-room-key":key.current,...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"The room is unavailable.");return d as T;}
async function signal(target:string,body:unknown){await api({action:"signal",target,body:JSON.stringify(body)});}
function clearPeer(id:string){pcs.current.get(id)?.close();pcs.current.delete(id);const a=audios.current.get(id);if(a){a.pause();a.srcObject=null;}audios.current.delete(id);ice.current.delete(id);setConnections([...pcs.current.values()].filter(p=>p.connectionState==="connected").length);}
function makePeer(id:string){let pc=pcs.current.get(id);if(pc)return pc;pc=new RTCPeerConnection({iceServers:(window as unknown as {BASEMENT_ICE_SERVERS:RTCIceServer[]}).BASEMENT_ICE_SERVERS||[{urls:"stun:stun.l.google.com:19302"}]});pcs.current.set(id,pc);stream.current?.getTracks().forEach(track=>pc!.addTrack(track,stream.current!));pc.onicecandidate=e=>{if(e.candidate)signal(id,{candidate:e.candidate.toJSON()}).catch(()=>{});};pc.ontrack=e=>{const a=new Audio();a.autoplay=true;a.muted=deafRef.current;a.srcObject=e.streams[0]||new MediaStream([e.track]);audios.current.set(id,a);a.play().catch(()=>toast("Tap the sound button to enable voice audio."));};pc.onconnectionstatechange=()=>{setConnections([...pcs.current.values()].filter(p=>p.connectionState==="connected").length);if(pc!.connectionState==="failed")toast.error("Voice could not connect on this network. A TURN relay may be needed. Leave voice and try again.",{duration:8000});};return pc;}
async function heartbeat(){if(!nameRef.current||!me.current)return;await api({action:"heartbeat",name:nameRef.current,voice:voiceRef.current});lastBeat.current=Date.now();}
async function poll(){if(!key.current||pollBusy.current)return;pollBusy.current=true;try{const activeRoom=roomRef.current;const d=await api(undefined,`?room=${activeRoom}&since=${since.current}`);me.current=d.me;if(activeRoom===roomRef.current)setMessages(d.messages);setPeers(d.peers);if(d.settings)setSettings(d.settings);setOnline(true);if(nameRef.current&&Date.now()-lastBeat.current>6000)await heartbeat();if(voiceRef.current&&stream.current){const others=(d.peers as Peer[]).filter(p=>p.voice===voiceRef.current&&p.id!==me.current);for(const id of pcs.current.keys())if(!others.some(p=>p.id===id))clearPeer(id);for(const p of others){if(me.current<p.id&&!pcs.current.has(p.id)){const pc=makePeer(p.id);await pc.setLocalDescription(await pc.createOffer());await signal(p.id,{description:pc.localDescription});}}
for(const s of d.signals){if(others.some(p=>p.id===s.sender)){try{const value=JSON.parse(s.body),pc=makePeer(s.sender);if(value.description){await pc.setRemoteDescription(value.description);for(const c of ice.current.get(s.sender)||[])await pc.addIceCandidate(c);ice.current.delete(s.sender);if(value.description.type==="offer"){await pc.setLocalDescription(await pc.createAnswer());await signal(s.sender,{description:pc.localDescription});}}else if(value.candidate){if(pc.remoteDescription)await pc.addIceCandidate(value.candidate);else ice.current.set(s.sender,[...(ice.current.get(s.sender)||[]),value.candidate]);}}catch{toast.error("Voice negotiation failed. Leave voice and rejoin.");}}since.current=Math.max(since.current,s.id);}}
else for(const s of d.signals)since.current=Math.max(since.current,s.id);
}catch{setOnline(false);}finally{pollBusy.current=false;}}
useEffect(()=>{const fragment=location.hash.slice(1);let k=/^[a-f0-9]{64}$/.test(fragment)?fragment:localStorage.getItem("basement-room:"+BASE);if(!k||!/^[a-f0-9]{64}$/.test(k))k=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,"0")).join("");key.current=k;localStorage.setItem("basement-room:"+BASE,k);history.replaceState(null,"","#"+k);setInviteUrl(location.href);const n=localStorage.getItem("basement-name:"+BASE)||"";setName(n);nameRef.current=n;setNameDraft(n);setReady(true);poll();const timer=setInterval(poll,2000);const hide=()=>{stream.current?.getTracks().forEach(t=>t.stop());fetch(BASE+"/api/lounge",{method:"POST",keepalive:true,headers:{"Content-Type":"application/json","x-room-key":key.current},body:JSON.stringify({action:"leave"})}).catch(()=>{});};window.addEventListener("pagehide",hide);return()=>{clearInterval(timer);window.removeEventListener("pagehide",hide);stream.current?.getTracks().forEach(t=>t.stop());pcs.current.forEach(p=>p.close());};},[]);
useEffect(()=>{if(bottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[messages]);
async function joinVoice(id:string){if(!name){setProfile(true);return;}if(joining)return;setJoining(true);try{if(voiceRef.current)await leaveVoice();const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});stream.current=s;voiceRef.current=id;setVoice(id);setMuted(false);await heartbeat();toast.success("You’re in "+voiceNames[voiceIds.indexOf(id)]);await poll();}catch(e){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;voiceRef.current="";setVoice("");toast.error(e instanceof DOMException&&e.name==="NotAllowedError"?"Allow microphone access in your browser to join voice.":"Could not join voice. Check your microphone and connection.");}finally{setJoining(false);}}
async function leaveVoice(){voiceRef.current="";setVoice("");stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;for(const id of [...pcs.current.keys()])clearPeer(id);setMuted(false);await heartbeat().catch(()=>{});}
function toggleMute(){stream.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(!muted);}
function toggleDeaf(){deafRef.current=!deaf;setDeaf(!deaf);audios.current.forEach(a=>{a.muted=deafRef.current;if(!deafRef.current)a.play().catch(()=>{});});}
async function send(e:React.FormEvent){e.preventDefault();if(!name){setProfile(true);return;}if(!text.trim()||sending)return;setSending(true);try{await api({action:"message",room,name,body:text});setText("");bottom.current=true;await poll();}catch(e){toast.error((e as Error).message);}finally{setSending(false);}}
async function save(){setSaving(true);try{await api({action:"settings",value:draft});setSettings(draft);setCustom(false);toast.success("The room has a new look.");}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
function selectRoom(r:string){roomRef.current=r;setRoom(r);setMessages([]);bottom.current=true;poll();}
function saveProfile(e:React.FormEvent){e.preventDefault();const n=nameDraft.trim().slice(0,24);if(!n)return;localStorage.setItem("basement-name:"+BASE,n);setName(n);nameRef.current=n;setProfile(false);heartbeat().catch(()=>toast.error("Your name is saved on this device. Reconnecting…"));}
async function copyInvite(){try{await navigator.clipboard.writeText(inviteUrl);toast.success("Room link copied");}catch{toast("Select and copy the room link below.");}}
const currentLabel=settings.labels[channels.indexOf(room)],display=custom?draft:settings;

const [decor,setDecor]=useState<Decor>(defaultDecor),[look,setLook]=useState<Look>(defaultLook),[players,setPlayers]=useState<Player[]>([]),[worldId,setWorldId]=useState(""),[editing,setEditing]=useState(false),[selected,setSelected]=useState(""),[visit,setVisit]=useState<string|null>(null),[files,setFiles]=useState<Asset[]>([]),[collection,setCollection]=useState<string|null>(null),[chatOpen,setChatOpen]=useState(false),[character,setCharacter]=useState(false),[addKind,setAddKind]=useState("sofa"),[playing,setPlaying]=useState<Asset|null>(null),[videoElement,setVideoElement]=useState<HTMLVideoElement|null>(null),[worldOnline,setWorldOnline]=useState(false),[decorBusy,setDecorBusy]=useState(false);
const position=useRef({x:0,z:3.6,r:Math.PI,seat:""}),lookRef=useRef(look),editRef=useRef(editing),serverDecor=useRef(defaultDecor);lookRef.current=look;editRef.current=editing;
async function refreshCollection(){const r=await fetch(BASE+"/api/library",{headers:{"x-room-key":key.current}});const d=await r.json() as {files:Asset[];decor:Decor|null;error?:string};if(!r.ok)throw new Error(d.error);setFiles(d.files);if(d.decor){serverDecor.current=d.decor;if(!editRef.current)setDecor(d.decor);}}
async function saveDecor(d:Decor){const r=await fetch(BASE+"/api/library",{method:"POST",headers:{"x-room-key":key.current,"Content-Type":"application/json"},body:JSON.stringify({action:"decor",value:d})});if(!r.ok)throw new Error("Could not save the room");setDecor(d);serverDecor.current=d;}
async function ensureJoined(){if(!nameRef.current){setProfile(true);return false;}try{await heartbeat();return true;}catch{toast.error("The room is reconnecting. Try again shortly.");return false;}}
function useObject(kind:string){if(["tv","console","arcade","books","speakers","art"].includes(kind))setCollection(kind);}
function visitKind(kind:string){const o=decor.objects.find(o=>o.kind===kind);if(o)setVisit(o.id);else if(kind==="art")setVisit("art-0");else setCollection(kind);}
useEffect(()=>{if(!ready)return;let disposed=false,busy=false,first=true;async function tick(){if(busy||disposed)return;busy=true;try{let r:Response;if(first){r=await fetch(BASE+"/api/world",{headers:{"x-room-key":key.current}});}else if(nameRef.current){r=await fetch(BASE+"/api/world",{method:"POST",headers:{"x-room-key":key.current,"Content-Type":"application/json"},body:JSON.stringify({...position.current,name:nameRef.current,look:lookRef.current})});}else{r=await fetch(BASE+"/api/world",{headers:{"x-room-key":key.current}});}const d=await r.json() as {me:string;look:Look|null;players:(Omit<Player,"look">&{look:string})[];seatTaken?:boolean};if(disposed)return;if(!r.ok){if(d.seatTaken){position.current.seat="";setVisit("__stand");toast("That seat was taken. Choose another spot.");}throw new Error();}setWorldId(d.me);setPlayers(d.players.map(p=>({...p,look:JSON.parse(p.look)})));if(first&&d.look){setLook(d.look);lookRef.current=d.look;}first=false;setWorldOnline(true);}catch{if(!disposed)setWorldOnline(false);}finally{busy=false;}}tick();refreshCollection().catch(()=>toast.error("Your collections could not load. Reopen a collection to retry."));const timer=setInterval(tick,900),collectionTimer=setInterval(()=>refreshCollection().catch(()=>{}),6000);const hide=()=>fetch(BASE+"/api/world",{method:"POST",keepalive:true,headers:{"x-room-key":key.current,"Content-Type":"application/json"},body:JSON.stringify({leave:true})}).catch(()=>{});window.addEventListener("pagehide",hide);return()=>{disposed=true;clearInterval(timer);clearInterval(collectionTimer);window.removeEventListener("pagehide",hide);};},[ready]);
const selectedObject=decor.objects.find(o=>o.id===selected);
function changeObject(delta:Partial<Decor["objects"][number]>){setDecor({...decor,objects:decor.objects.map(o=>o.id===selected?{...o,...delta}:o)});}
return <div className="iso-app" style={{"--primary":decor.neon,"--glow":decor.neon} as CSSProperties}><Toaster theme="dark" position="top-center" richColors/>
<a className="host-signout" href={BASE+"/logout.php"}>Sign out</a><header className="iso-header"><div className="iso-brand"><span className="pixel-logo"><Gamepad2 size={28}/></span><div><strong>{settings.title}</strong><small>YOUR OWN LITTLE WORLD</small></div></div><div className="iso-top-actions"><span className="online-count"><span className={worldOnline?"live-dot":"offline-dot"}/>{players.length} in room</span><button className="retro-button" onClick={()=>setCharacter(true)}><Shirt size={17}/><span>Character</span></button><button className={"retro-button "+(editing?"bright":"")} onClick={()=>{if(editing){setDecor(serverDecor.current);setEditing(false);}else setEditing(true);}}><Move size={17}/><span>{editing?"Cancel edit":"Decorate"}</span></button><button className="retro-button" onClick={()=>setInvite(true)}><LinkIcon size={17}/><span>Invite</span></button></div></header>
<BasementWorld title={settings.title} sign={settings.poster} light={settings.light} scanlines={settings.scanlines} decor={decor} players={players} selfId={worldId} look={look} name={name} editing={editing} selected={selected} visit={visit} video={videoElement} onVisitDone={()=>setVisit(null)} onInteract={useObject} onSelect={setSelected} onMotion={p=>{position.current=p;}} onNeedName={()=>setProfile(true)}/>
{!name&&<button className="join-room-prompt" onClick={()=>setProfile(true)}><span className="pixel-spark">✦</span> Choose your name and step inside <ArrowUpRight size={18}/></button>}
{editing&&<aside className="decorate-panel"><div className="editor-heading"><h2><Move size={18}/>ROOM EDITOR</h2><button aria-label="Close room editor" onClick={()=>{setDecor(serverDecor.current);setEditing(false);}}><X size={18}/></button></div><div className="colour-row">{(["wall","floor","neon"] as const).map(k=><label key={k}>{k}<input type="color" value={decor[k]} onChange={e=>setDecor({...decor,[k]:e.target.value})}/></label>)}</div><label>Furniture<Select value={selected||"none"} onValueChange={v=>setSelected(v==="none"?"":v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Select an item</SelectItem>{decor.objects.map((o,i)=><SelectItem key={o.id} value={o.id}>{furnitureNames[o.kind]} {i+1}</SelectItem>)}</SelectContent></Select></label>{selectedObject&&<><label>Across room<Slider value={[selectedObject.x]} min={-5.5} max={5.5} step={.25} onValueChange={v=>changeObject({x:v[0]})}/></label><label>Along room<Slider value={[selectedObject.z]} min={-4.5} max={4.5} step={.25} onValueChange={v=>changeObject({z:v[0]})}/></label><div className="editor-row"><button className="retro-button" onClick={()=>changeObject({r:(selectedObject.r+90)%360})}><RotateCw size={15}/>Rotate</button><button className="retro-button" onClick={()=>{setDecor({...decor,objects:decor.objects.filter(o=>o.id!==selected)});setSelected("");}}>Remove</button></div></>}<label>Add furniture<Select value={addKind} onValueChange={setAddKind}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(furnitureNames).map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select></label><button className="retro-button" disabled={decor.objects.length>=24} onClick={()=>{const id=crypto.randomUUID();setDecor({...decor,objects:[...decor.objects,{id,kind:addKind,x:2,z:2,r:0}]});setSelected(id);}}><Plus size={16}/>Place in room</button><button className="retro-button bright" disabled={decorBusy} onClick={async()=>{setDecorBusy(true);try{await saveDecor(decor);setEditing(false);toast.success("Room saved for everyone");}catch{toast.error("Could not save. Your changes are still here.");}finally{setDecorBusy(false);}}}><Save size={16}/>{decorBusy?"Saving…":"Save room"}</button><p>Everyone in this room shares the layout. Up to 24 furniture items.</p></aside>}
<div className="room-bottom"><div className="player-badge" onClick={()=>setCharacter(true)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")setCharacter(true);}}><span className="avatar" style={{background:look.top,color:look.skin}}><Shirt size={21}/></span><span><strong>{name||"Guest"}</strong><small>{voice?"In voice · "+voiceNames[voiceIds.indexOf(voice)]:"Click to customise"}</small></span></div><nav className="object-dock" aria-label="Room objects">{[{k:"tv",label:"TV",Icon:Tv},{k:"console",label:"Consoles",Icon:Gamepad2},{k:"arcade",label:"Arcade",Icon:Radio},{k:"books",label:"Books",Icon:BookOpen},{k:"art",label:"Artwork",Icon:ImageIcon}].map(({k,label,Icon})=><button key={k} onClick={()=>visitKind(k)}><Icon size={23}/><span>{label}</span></button>)}</nav><div className="social-dock"><button onClick={()=>setChatOpen(true)} aria-label="Open chat"><MessageCircle size={22}/><span>Chat</span></button><button onClick={()=>voice?leaveVoice():joinVoice("couch")} aria-label={voice?"Leave voice":"Join voice"} className={voice?"voice-active":""}><Headphones size={22}/><span>{voice?"In voice":"Voice"}</span></button><button onClick={()=>{setDraft(settings);setCustom(true);}} aria-label="Room settings"><Settings size={21}/></button></div></div>
{voice&&<div className="iso-voice"><span className="live-dot"/><span>{connections?`${connections} connected`:"Waiting for friends"}</span><button onClick={toggleMute} aria-label={muted?"Unmute":"Mute"}>{muted?<MicOff size={17}/>:<Mic size={17}/>}</button><button onClick={toggleDeaf} aria-label={deaf?"Enable sound":"Mute sound"}>{deaf?<VolumeX size={17}/>:<Volume2 size={17}/>}</button><button onClick={leaveVoice} aria-label="Leave voice"><PhoneOff size={17}/></button></div>}
{playing&&<section className="now-playing"><div><strong>{playing.filename}</strong><button onClick={()=>{setPlaying(null);setVideoElement(null);}} aria-label="Stop playback"><X size={17}/></button></div><video ref={setVideoElement} key={playing.id} src={BASE+"/api/files/"+playing.id} controls autoPlay playsInline onError={()=>toast.error("This file could not play. Check that its codec is supported by your browser.")}/><span>Playing on your TV · personal playback</span></section>}
<RoomCollection kind={collection} setKind={k=>{setCollection(k);if(k)refreshCollection().catch(()=>{});}} files={files} roomKey={key.current} ensureJoined={ensureJoined} refresh={refreshCollection} decor={decor} saveDecor={saveDecor} onPlay={setPlaying} playing={playing} video={videoElement}/>
<Dialog open={character} onOpenChange={setCharacter}><DialogContent className="character-window"><DialogTitle>YOUR CHARACTER</DialogTitle><DialogDescription>Everyone in the room sees your outfit. Changes save while you’re connected.</DialogDescription><button className="retro-button" onClick={()=>{setCharacter(false);setNameDraft(name);setProfile(true);}}>Display name: {name||"Choose a name"}</button><div className="character-colours">{(["skin","hair","top","bottom"] as const).map(k=><label key={k}>{k==="top"?"Shirt":k==="bottom"?"Trousers":k}<input type="color" value={look[k]} onChange={e=>setLook({...look,[k]:e.target.value})}/></label>)}</div><label>Hair / headwear<Select value={String(look.style)} onValueChange={v=>setLook({...look,style:Number(v)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0">Short hair</SelectItem><SelectItem value="1">Long hair</SelectItem><SelectItem value="2">Cap</SelectItem></SelectContent></Select></label><button className="retro-button bright" onClick={()=>setCharacter(false)}>Back to the room</button>{!worldOnline&&<p className="collection-note">Reconnecting — outfit changes have not saved yet.</p>}</DialogContent></Dialog>
<Dialog open={chatOpen} onOpenChange={setChatOpen}><DialogContent className="room-chat-window"><DialogTitle>ROOM CHAT</DialogTitle><DialogDescription>{settings.topic}</DialogDescription><nav className="chat-tabs">{channels.map((r,i)=><button key={r} onClick={()=>selectRoom(r)} className={room===r?"active":""}># {settings.labels[i]}</button>)}</nav><div className="messages" ref={scroll} aria-live="polite">{messages.length===0?<div className="empty-chat"><h3>Say hello to the room.</h3><p>Your conversations stay saved here.</p></div>:messages.map(m=><div className="message" key={m.id}><span className="avatar">{m.name.slice(0,2).toUpperCase()}</span><div><div className="message-meta"><strong>{m.name}</strong><time>{new Date(m.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div><p>{m.body}</p></div></div>)}</div><form className="composer" onSubmit={send}><input aria-label="Message" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder={"Message #"+currentLabel}/><button type="submit" aria-label="Send message" disabled={!text.trim()||sending||!online}><Send size={18}/></button></form><div className="voice-rooms">{voiceIds.map((v,i)=><button key={v} className="retro-button" disabled={joining} onClick={()=>joinVoice(v)}><Headphones size={15}/>{voiceNames[i]}</button>)}</div></DialogContent></Dialog>
<Dialog open={custom} onOpenChange={setCustom}><DialogContent className="settings-modal"><DialogTitle>Make it your basement.</DialogTitle><DialogDescription>Room details are shared. Everyone with this room link can customise them.</DialogDescription><label>Hangout name<input value={draft.title} maxLength={36} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Room topic<input value={draft.topic} maxLength={120} onChange={e=>setDraft({...draft,topic:e.target.value})}/></label><label>Room lighting <span>{draft.light}%</span><Slider aria-label="Room lighting" min={40} max={110} step={1} value={[draft.light]} onValueChange={v=>setDraft({...draft,light:v[0]})}/></label><label>Room sign<input value={draft.poster} maxLength={40} onChange={e=>setDraft({...draft,poster:e.target.value})}/></label><div className="settings-row"><label htmlFor="scanlines">CRT scanlines</label><Switch id="scanlines" checked={draft.scanlines} onCheckedChange={v=>setDraft({...draft,scanlines:v})}/></div><div className="channel-fields">{draft.labels.map((v,i)=><label key={i}>Channel {i+1}<input value={v} maxLength={24} onChange={e=>setDraft({...draft,labels:draft.labels.map((l,j)=>j===i?e.target.value:l)})}/></label>)}</div><div className="modal-actions"><button onClick={()=>setDraft(defaults)}>Reset look</button><button className="primary-button" disabled={saving||!online} onClick={save}>{saving?"Saving…":"Save changes"}</button></div></DialogContent></Dialog>
<Dialog open={profile} onOpenChange={setProfile}><DialogContent><DialogTitle>Who’s coming downstairs?</DialogTitle><DialogDescription>Choose the name your friends will see in chat and voice rooms.</DialogDescription><form onSubmit={saveProfile}><label>Display name<input autoFocus maxLength={24} value={nameDraft} onChange={e=>setNameDraft(e.target.value)} required placeholder="Your nickname"/></label><button className="primary-button full" type="submit">Take a seat</button></form></DialogContent></Dialog>
<Dialog open={invite} onOpenChange={setInvite}><DialogContent><DialogTitle>Good company starts here.</DialogTitle><DialogDescription>Friends need access to the site and this exact room link. Keep it within your group: it opens the shared chat and room settings.</DialogDescription><label>Room link<input readOnly value={inviteUrl} onFocus={e=>e.target.select()}/></label><button className="primary-button" onClick={copyInvite}><LinkIcon size={17}/>Copy room link</button><p className="quiet-copy">Share your guest access password with friends as well as this room link.</p><p className="quiet-copy">Voice uses your microphone and a direct browser connection. Some networks require a TURN relay. Two-device calling has not been verified yet.</p></DialogContent></Dialog>
</div>;
}
