<?php
require __DIR__.'/private/bootstrap.php';
function players(string $space): array {$out=rows('SELECT * FROM room_players WHERE space=? AND at>? ORDER BY id',[$space,now_ms()-15000]);foreach($out as &$p){foreach(['x','z','r'] as $n)$p[$n]=(float)$p[$n];$p['at']=(int)$p['at'];$p['seat']=$p['seat']??'';}return $out;}
function file_response(string $id): never {
 $a=auth(true);if(!valid_id($id))fail('File not found.',404);$f=row('SELECT a.* FROM assets a JOIN peers p ON a.space=p.space WHERE a.id=? AND p.id=?',[$id,$a['id']]);if(!$f)fail('File not found in this room.',404);$path=storage_file($id);if(!is_file($path))fail('File unavailable.',404);$size=(int)$f['size'];$start=0;$end=$size-1;$partial=false;$range=$_SERVER['HTTP_RANGE']??'';
 if($range!==''){if(!preg_match('/^bytes=(\d*)-(\d*)$/D',$range,$m)||($m[1]===''&&$m[2]==='')){header('Content-Range: bytes */'.$size);http_response_code(416);exit;}if($m[1]!==''){$start=(int)$m[1];if($m[2]!=='')$end=min($end,(int)$m[2]);}else{$start=max(0,$size-(int)$m[2]);}if($start>$end||$start>=$size){header('Content-Range: bytes */'.$size);http_response_code(416);exit;}$partial=true;}
 http_response_code($partial?206:200);header('Content-Type: '.$f['mime']);header('Content-Length: '.($end-$start+1));header('Accept-Ranges: bytes');header('Cache-Control: private, no-store');header('X-Content-Type-Options: nosniff');header('Content-Security-Policy: sandbox');header("Content-Disposition: ".($f['mime']==='application/octet-stream'?'attachment':'inline')."; filename*=UTF-8''".rawurlencode($f['filename']));if($partial)header("Content-Range: bytes $start-$end/$size");if($_SERVER['REQUEST_METHOD']==='HEAD')exit;
 while(ob_get_level())ob_end_clean();@set_time_limit(0);$h=fopen($path,'rb');fseek($h,$start);$left=$end-$start+1;while($left>0&&!feof($h)&&!connection_aborted()){$piece=fread($h,min(1048576,$left));if($piece===false||$piece==='')break;echo $piece;$left-=strlen($piece);flush();}fclose($h);exit;
}
try{
 $route=$_GET['route']??'';$method=$_SERVER['REQUEST_METHOD'];if($route==='files'){if(!in_array($method,['GET','HEAD'],true))fail('Method not allowed.',405);file_response((string)($_GET['id']??''));}
 [$id,$space]=api_context();$now=now_ms();
 if($route==='lounge'){
  if($method==='GET'){$room=(string)($_GET['room']??'general');$since=max(0,(int)($_GET['since']??0));$m=array_reverse(rows('SELECT id,name,body,at,sender FROM messages WHERE space=? AND room=? ORDER BY id DESC LIMIT 100',[$space,$room]));foreach($m as &$message){$message['id']=(int)$message['id'];$message['at']=(int)$message['at'];}$s=rows('SELECT id,sender,body FROM signals WHERE space=? AND target=? AND id>? AND at>? ORDER BY id LIMIT 150',[$space,$id,$since,$now-60000]);foreach($s as &$signal)$signal['id']=(int)$signal['id'];$c=row('SELECT value FROM settings WHERE space=?',[$space]);json_out(['me'=>$id,'messages'=>$m,'peers'=>rows('SELECT id,name,voice FROM peers WHERE space=? AND at>? ORDER BY name',[$space,$now-20000]),'signals'=>$s,'settings'=>$c?json_decode($c['value'],true):null]);}
  if($method!=='POST')fail('Method not allowed.',405);$b=body_json();$action=$b['action']??'';$name=cut(trim((string)($b['name']??'Guest')),24);
  if($action==='heartbeat'){if($name==='')fail('Choose a display name.');put_row('peers',['id'=>$id],['space'=>$space,'name'=>$name,'voice'=>in_array($b['voice']??'',['couch','arcade','quiet'],true)?$b['voice']:'','at'=>$now]);json_out(['ok'=>true]);}
  if($action==='leave'){query('DELETE FROM peers WHERE id=? AND space=?',[$id,$space]);json_out(['ok'=>true]);}
  if($action==='message'){$text=trim((string)($b['body']??''));if(!$name||!$text||mb_strlen($text)>2000||!in_array($b['room']??'',['general','game-night','off-topic'],true))fail('Add a message up to 2,000 characters.');$last=row('SELECT at FROM messages WHERE space=? AND sender=? ORDER BY id DESC LIMIT 1',[$space,$id]);if($last&&$now-$last['at']<700)fail('Give it a moment before sending again.',429);query('INSERT INTO messages(space,room,sender,name,body,at) VALUES(?,?,?,?,?,?)',[$space,$b['room'],$id,$name,$text,$now]);json_out(['ok'=>true]);}
  if($action==='settings'){$v=$b['value']??[];if(!is_string($v['title']??null)||!is_string($v['topic']??null)||!colour($v['accent']??null)||!is_array($v['labels']??null)||count($v['labels'])!==3)fail('Check the room details.');foreach($v['labels'] as $label)if(!is_string($label)||!trim($label)||mb_strlen($label)>24)fail('Check the channel names.');$value=['title'=>cut(trim($v['title']),36)?:'The Basement','topic'=>cut(trim($v['topic']),120),'accent'=>$v['accent'],'labels'=>array_values($v['labels']),'light'=>max(40,min(110,(int)($v['light']??85))),'poster'=>cut($v['poster']??'INSERT COIN',40),'scanlines'=>(bool)($v['scanlines']??false)];put_row('settings',['space'=>$space],['value'=>json_encode($value)]);json_out(['ok'=>true]);}
  if($action==='signal'){$target=(string)($b['target']??'');$body=$b['body']??null;if(!is_string($body)||strlen($body)>16000)fail('Invalid voice signal.');$from=row('SELECT voice FROM peers WHERE id=? AND space=? AND at>?',[$id,$space,$now-20000]);$to=row('SELECT voice FROM peers WHERE id=? AND space=? AND at>?',[$target,$space,$now-20000]);if(empty($from['voice'])||($from['voice']!==($to['voice']??'')))fail('Voice room changed. Rejoin voice.',409);query('INSERT INTO signals(space,sender,target,body,at) VALUES(?,?,?,?,?)',[$space,$id,$target,$body,$now]);query('DELETE FROM signals WHERE space=? AND at<?',[$space,$now-120000]);json_out(['ok'=>true]);}
 }
 if($route==='world'){
  if($method==='GET'){$p=row('SELECT look FROM room_players WHERE id=?',[$id]);json_out(['me'=>$id,'look'=>$p?json_decode($p['look'],true):null,'players'=>players($space)]);}
  if($method!=='POST')fail('Method not allowed.',405);$b=body_json(3000);if(!empty($b['leave'])){query('UPDATE room_players SET at=0,seat=NULL WHERE id=?',[$id]);json_out(['ok'=>true]);}
  foreach(['x','z','r'] as $n)if(!isset($b[$n])||!is_numeric($b[$n])||!is_finite((float)$b[$n]))fail('Invalid character position.');$look=$b['look']??[];foreach(['skin','hair','top','bottom'] as $k)if(!colour($look[$k]??null))fail('Check character colours.');if(!in_array($look['style']??null,[0,1,2],true)||!trim($b['name']??''))fail('Check character details.');$seat=cut($b['seat']??'',60);$seat=$seat===''?null:$seat;
  db()->beginTransaction();try{query('UPDATE room_players SET seat=NULL WHERE space=? AND at<? AND seat IS NOT NULL',[$space,$now-15000]);put_row('room_players',['id'=>$id],['space'=>$space,'name'=>cut(trim($b['name']),24),'x'=>max(-5.7,min(5.7,(float)$b['x'])),'z'=>max(-4.7,min(4.7,(float)$b['z'])),'r'=>(float)$b['r'],'seat'=>$seat,'look'=>json_encode($look),'at'=>$now]);db()->commit();}catch(PDOException $e){if(db()->inTransaction())db()->rollBack();if(str_contains(strtolower($e->getMessage()),'unique')||str_contains(strtolower($e->getMessage()),'duplicate'))json_out(['error'=>'That seat is taken. Choose another seat.','seatTaken'=>true],409);throw $e;}
  json_out(['me'=>$id,'players'=>players($space)]);
 }
 if($route==='library'){
  if($method==='GET'){$files=rows('SELECT * FROM assets WHERE space=? ORDER BY created DESC LIMIT 500',[$space]);foreach($files as &$f){$f['size']=(int)$f['size'];$f['created']=(int)$f['created'];}$decor=row('SELECT value FROM room_decor WHERE space=?',[$space]);json_out(['files'=>$files,'decor'=>$decor?json_decode($decor['value'],true):null]);}
  if($method==='PUT'){
   $upload=(string)($_GET['id']??'');$part=filter_var($_GET['part']??0,FILTER_VALIDATE_INT);if(!valid_id($upload)||!$part||$part<1)fail('Invalid upload chunk.');$lock=fopen(config()['storage'].'/incoming/'.$upload.'.lock','c');flock($lock,LOCK_EX);$u=row('SELECT * FROM uploads WHERE id=? AND space=?',[$upload,$space]);if(!$u)fail('Upload not found.',404);$meta=json_decode($u['meta'],true);$offset=($part-1)*CHUNK_BYTES;$expected=min(CHUNK_BYTES,$meta['size']-$offset);if($expected<1||$part>ceil($meta['size']/CHUNK_BYTES))fail('Invalid chunk number.');if((int)($_SERVER['CONTENT_LENGTH']??0)!==$expected)fail('Upload chunk size mismatch.');
   if((int)$u['uploaded']>=$offset+$expected){flock($lock,LOCK_UN);fclose($lock);json_out(['ok'=>true]);}if((int)$u['uploaded']!==$offset)fail('Upload chunks must arrive in order.',409);
   $path=storage_file($upload,true);$out=fopen($path,'c+b');if(!$out)fail('Could not open upload storage.',503);ftruncate($out,$offset);fseek($out,$offset);$in=fopen('php://input','rb');$written=stream_copy_to_stream($in,$out,$expected+1);fclose($in);fflush($out);if($written!==$expected){ftruncate($out,$offset);fclose($out);fail('The upload was interrupted. Retry this file.',503);}fclose($out);query('UPDATE uploads SET uploaded=? WHERE id=? AND space=?',[$offset+$expected,$upload,$space]);flock($lock,LOCK_UN);fclose($lock);json_out(['ok'=>true]);
  }
  if($method!=='POST')fail('Method not allowed.',405);$b=body_json(16000);$action=$b['action']??'';
  if($action==='start'){$filename=cut(preg_replace('/[\/\\\\\x00-\x1f]/','_',basename((string)($b['filename']??''))),150);$kind=(string)($b['kind']??'');$size=$b['size']??0;if(!is_int($size)||$size<1||$size>file_limit($kind)||!$filename)fail('File size is invalid. ROMs allow 16 GB, media 1 GB, other files 32 MB.');$mime=classify($filename,$kind);$core=in_array($b['core']??'',['nes','snes','gb','gba','segaMD','n64','psx','arcade'],true)?$b['core']:'nes';$count=row('SELECT COUNT(*) AS n FROM assets WHERE space=?',[$space]);if($count['n']>=500)fail('This room has 500 files. Remove a file before adding another.');$free=disk_free_space(config()['storage']);if($free!==false&&$size>$free-16777216)fail('Not enough free hosting storage for this file.',507);$uid=uuid();query('INSERT INTO uploads(id,space,meta,uploaded,created) VALUES(?,?,?,?,?)',[$uid,$space,json_encode(['filename'=>$filename,'kind'=>$kind,'size'=>$size,'core'=>$core,'mime'=>$mime]),0,$now]);json_out(['id'=>$uid]);}
  if($action==='finish'||$action==='cancel'){$uid=(string)($b['id']??'');if(!valid_id($uid))fail('Invalid upload.');$lock=fopen(config()['storage'].'/incoming/'.$uid.'.lock','c');flock($lock,LOCK_EX);$u=row('SELECT * FROM uploads WHERE id=? AND space=?',[$uid,$space]);if(!$u){if($action==='finish'&&row('SELECT id FROM assets WHERE id=? AND space=?',[$uid,$space]))json_out(['ok'=>true]);fail('Upload not found.',404);}$path=storage_file($uid,true);if($action==='cancel'){if(is_file($path))unlink($path);query('DELETE FROM uploads WHERE id=? AND space=?',[$uid,$space]);json_out(['ok'=>true]);}$m=json_decode($u['meta'],true);if((int)$u['uploaded']!==$m['size']||!is_file($path)||filesize($path)!==$m['size'])fail('Upload is incomplete. Please retry.');$dest=storage_file($uid);if(!rename($path,$dest))fail('Could not finish storing this file.',503);try{query('INSERT INTO assets(id,space,kind,filename,mime,size,core,created) VALUES(?,?,?,?,?,?,?,?)',[$uid,$space,$m['kind'],$m['filename'],$m['mime'],$m['size'],$m['core'],$now]);query('DELETE FROM uploads WHERE id=? AND space=?',[$uid,$space]);}catch(Throwable $e){rename($dest,$path);throw $e;}flock($lock,LOCK_UN);fclose($lock);json_out(['ok'=>true]);}
  if($action==='delete'){$uid=(string)($b['id']??'');if(!row('SELECT id FROM assets WHERE id=? AND space=?',[$uid,$space]))fail('File not found.',404);$path=storage_file($uid);if(is_file($path)&&!unlink($path))fail('Could not remove the stored file.',503);query('DELETE FROM assets WHERE id=? AND space=?',[$uid,$space]);json_out(['ok'=>true]);}
  if($action==='decor'){$d=$b['value']??[];foreach(['wall','floor','neon'] as $k)if(!colour($d[$k]??null))fail('Check room colours.');if(!is_array($d['objects']??null)||count($d['objects'])>24||!is_array($d['art']??null)||count($d['art'])>3)fail('Check the room layout.');$objects=[];$ids=[];foreach($d['objects'] as $o){if(!in_array($o['kind']??'',['tv','console','arcade','books','sofa','plant','lamp','table','speakers'],true)||!is_string($o['id']??null)||strlen($o['id'])>50||isset($ids[$o['id']]))fail('Invalid furniture.');foreach(['x','z','r'] as $k)if(!is_numeric($o[$k]??null)||!is_finite((float)$o[$k]))fail('Invalid furniture position.');$ids[$o['id']]=true;$objects[]=['id'=>$o['id'],'kind'=>$o['kind'],'x'=>max(-5.5,min(5.5,(float)$o['x'])),'z'=>max(-4.5,min(4.5,(float)$o['z'])),'r'=>fmod(fmod((float)$o['r'],360)+360,360)];}$art=array_map(fn($v)=>is_string($v)&&valid_id($v)?$v:'',$d['art']);put_row('room_decor',['space'=>$space],['value'=>json_encode(['wall'=>$d['wall'],'floor'=>$d['floor'],'neon'=>$d['neon'],'objects'=>$objects,'art'=>$art])]);json_out(['ok'=>true]);}
 }
 fail('Unknown action.',400);
}catch(Throwable $e){error_log('Basement API: '.$e->getMessage());if(isset($GLOBALS['db'])&&$GLOBALS['db']->inTransaction())$GLOBALS['db']->rollBack();fail('The server could not complete this request. Please retry.',503);}
